### ISSUE TITLE
WARNING message: No meaningful fit was possible

### ISSUE THREAD

**Issue by Ragadeepika-Pucha** [astropy/photutils-datasets#16]
Hi,

I am trying to fit an ellipse to a galaxy. It is highly resolved data from HyperSuprimeCam, Subaru Telescope. I am getting the message - WARNING: No meaningful fit was possible. [photutils.isophote.ellipse]. Is there something I should look at? Or is it hard to fit ellipse to resolved data?

Please help.
Thanks

**Comment by ibusko** [comment]
@larrybradley Sure. I'll look into it.

**Comment by ibusko** [comment]
@Ragadeepika-Pucha here is the comment in the source code that emits that warning message. It suggests that initial values provided to the fit algorithm are too way off and result in a divergency situation.
`                # in case the fit failed right at the outset, return an
                  # empty list. This is the usual case when the user
                  # provides initial guesses that are too way off to enable
                  # the fitting algorithm to find any meaningful solution.`

Did you manage to get fits from the same image before?

**Comment by Ragadeepika-Pucha** [comment]
@ibusko I did not get the fits at all. I could see the ellipse contours on ds9, but couldn't get them in python. 

I did not give the fits any intial values - can you please suggest me what all intial values go into the code?

Thanks.

**Comment by larrybradley** [comment]
Please open an issue on the photutils issue tracker if you are still having an issue:  https://github.com/astropy/photutils/issues
