### ISSUE TITLE
Notebook not working anymore with 0.7.2

### ISSUE THREAD

**Issue by bcarry** [astropy/photutils-datasets#18]
Hi

First, thanks a lot for photutils, it's very convenient.
I was trying to make PSF Fitting work, and wanted to use the 2 jupyter notebooks:
GaussianPSFPhot.ipynb
and
ArtificialCrowdedFieldPSFPhotometry.ipynb

However, these appear to have been written for photutils 0.3, while current release is 0.7.2
As the API changed (datasets module for instance, psf.psf_photometry, ...), the notebooks are no longer working. 
If I could, I would offer a correction, but as I'm trying to understand how to use photutils for PSF fitting, I am stuck.

If you can update the notebooks, it would be very much appreciated.
Thanks

**Comment by larrybradley** [comment]
Thanks, @bcarry.  I've updated the `ArtificialCrowdedFieldPSFPhotometry.ipynb`.  The other notebook was hopelessly out of date, so I removed it.
