### ISSUE TITLE
Use photutils source detection in Spitzer PRF photometry notebook

### ISSUE THREAD

**Issue by adonath** [astropy/photutils-datasets#4]
It would make sense to use the photutils source detection functionality in the [Spitzer PRF photometry notebook](http://nbviewer.ipython.org/github/astropy/photutils-datasets/blob/master/notebooks/PSFPhotometrySpitzer.ipynb), because it is actually part of the procedure to detect the sources first.  Also the positions in the reference catalog seem to be slightly offset and possibly more accurate results could be achieved by estimating the source positions again.

**Comment by banados** [comment]
I was looking into this notebook, it looks like very useful and instructive. However,  it actually does not work with the latest versions of photutils (i.e., >0.3). 

I've tried it with v0.3 and the '0.4.dev2300' 

and simple things like 
  
    from photutils.psf import create_prf
    from photutils.psf import psf_photometry
    from photutils.psf import GaussianPSF

are not supported anymore. Does anybody know if there are efforts ongoing to make it work with the latest developments?

Thanks!

**Comment by cdeil** [comment]
@banados - Thanks for the comment.

If someone has time to update this notebook, please do.

I don't and I don't think @adonath does.

There's also #9 that notebooks should be tested, either automatically, or as one of the steps on a checklist before cutting a release.

There's also an open PR about a different notebook I think: #7

cc @larrybradley @bsipocz as photutils maintainers

**Comment by larrybradley** [comment]
@mirca and @eteq:  Are there any plans to update this notebook?  If not, we should remove it since it no longer works.

**Comment by mirca** [comment]
@larrybradley @eteq I'm gonna update this notebook to work with the new PSF photometry classes.

**Comment by larrybradley** [comment]
Thanks, @mirca!

**Comment by banados** [comment]
Thanks @mirca ! Please let us know when you have an updated version, I'd be very interested to have a look at it.

**Comment by bsipocz** [comment]
@banados - I've just merged the updates to the other notebook ``ArtificialCrowdedFieldPSFPhotometry.ipynb``, you may want to have a look at that while this is being worked on.

**Comment by Gabriel-p** [comment]
I'm trying to modify this notebook to work with the latest version of `photutils`, here: https://github.com/Gabriel-p/photutils-datasets

The old `photutils.psf.psf_photometry` version apparently made a lot of assumptions about the PSF process that are no longer allowed. For example, this simple command

    psf_photometry(data, coords, prf_discrete)

returned fluxes that matched the true ones very good

![descarga](https://user-images.githubusercontent.com/6054951/32905274-3765401e-cad8-11e7-9edd-2a96d52939b8.png)

With the new version, using `BasicPSFPhotometry`, I have to give values for at least these seven parameters:

```
fwhm = 3.
crit_separation = 2.
daogroup = DAOGroup(crit_separation * fwhm)
bkg = MMMBackground()
fitshape=(11, 11)
aperture_radius=5
fitter=LevMarLSQFitter()
```

where the values above result in

![descarga 1](https://user-images.githubusercontent.com/6054951/32905425-ae8b79e2-cad8-11e7-89a1-15a2dd2e6971.png)

What would be reasonable values for the above parameters to match the accuracy of the old default values?

**Comment by Gabriel-p** [comment]
No one can help shed some light on this?

**Comment by larrybradley** [comment]
Ping: @mirca?

**Comment by mirca** [comment]
Thanks for pinging me here, @larrybradley. I’m gonna take a look at this later this week!

**Comment by mirca** [comment]
@Gabriel-p could you sort the psf photometry table by `id` before making the plot?

**Comment by Gabriel-p** [comment]
Much better! It was a really simple fix after all, I guess the old class did not change the order of the input sources? Here's the new output:

![descarga](https://user-images.githubusercontent.com/6054951/33574092-89c2cc68-d8fd-11e7-867e-3d6f9f691e43.png)

I can keep working on that notebook now, than you @mirca!

**Comment by mirca** [comment]
@Gabriel-p Awesome! Glad that it helps!
