### ISSUE TITLE
Update needed?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils-datasets#8]
The `DAOPhotPSFPhotometry` class requires different input as far as I can tell:

```
daophot_photometry = DAOPhotPSFPhotometry(finder=iraffind, group_maker=daogroup,
                                          bkg_estimator=mmm_bkg, psf_model=psf_model,
                                          fitter=LevMarLSQFitter(),
                                          niters=2, fitshape=(11,11))
```

**Comment by bsipocz** [comment]
Closing this, as ``ArtificialCrowdedFieldPSFPhotometry.ipynb`` has been updates.

@Gabriel-p - please have a look at it.

**Comment by Gabriel-p** [comment]
The doc [says](http://nbviewer.jupyter.org/github/astropy/photutils-datasets/blob/master/notebooks/ArtificialCrowdedFieldPSFPhotometry.ipynb#Perform-photometry):

> To perform PSF photometry, we need first to initialize a DAOPhotPSFPhotometry object 

but no `DAOPhotPSFPhotometry` is initialized?
